version: "3.1"
services:
    www:
        build: .
        ports: 
            - "22522:5000"
        volumes:
            - ./webnya:/sorcery:ro
            - ./webnya/website/static/images:/sorcery/website/static/images
            - ./magic_portal_34526235:/magic_portal_34526235:ro
        networks:
            - default
        tty: true 
volumes:
    persistent:
