version: "3.1"
services:
    www:
        build: .
        ports: 
            - "5000:5000"
        volumes:
            - .:/sorcery
        networks:
            - default
        tty: true 
volumes:
    persistent:
