version: "3.1"
services:
    www:
        build: .
        ports: 
            - "5000:5000"
        volumes:
            - ./website:/sorcery
            - ./magic_portal_34526235:/magic_portal_34526235
        networks:
            - default
        tty: true 
volumes:
    persistent:
